// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/khoihuynh300/go-microservice/user-service/internal/security/jwtprovider (interfaces: JwtProvider)

// Package mock_jwt is a generated GoMock package.
package mock_jwt

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	models "github.com/khoihuynh300/go-microservice/user-service/internal/domain/models"
	jwtprovider "github.com/khoihuynh300/go-microservice/user-service/internal/security/jwtprovider"
)

// MockJwtProvider is a mock of JwtProvider interface.
type MockJwtProvider struct {
	ctrl     *gomock.Controller
	recorder *MockJwtProviderMockRecorder
}

// MockJwtProviderMockRecorder is the mock recorder for MockJwtProvider.
type MockJwtProviderMockRecorder struct {
	mock *MockJwtProvider
}

// NewMockJwtProvider creates a new mock instance.
func NewMockJwtProvider(ctrl *gomock.Controller) *MockJwtProvider {
	mock := &MockJwtProvider{ctrl: ctrl}
	mock.recorder = &MockJwtProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJwtProvider) EXPECT() *MockJwtProviderMockRecorder {
	return m.recorder
}

// GenerateAccessToken mocks base method.
func (m *MockJwtProvider) GenerateAccessToken(arg0 *models.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockJwtProviderMockRecorder) GenerateAccessToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockJwtProvider)(nil).GenerateAccessToken), arg0)
}

// GenerateRefreshToken mocks base method.
func (m *MockJwtProvider) GenerateRefreshToken(arg0 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockJwtProviderMockRecorder) GenerateRefreshToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockJwtProvider)(nil).GenerateRefreshToken), arg0)
}

// GetRefreshTTL mocks base method.
func (m *MockJwtProvider) GetRefreshTTL() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRefreshTTL")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetRefreshTTL indicates an expected call of GetRefreshTTL.
func (mr *MockJwtProviderMockRecorder) GetRefreshTTL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRefreshTTL", reflect.TypeOf((*MockJwtProvider)(nil).GetRefreshTTL))
}

// VerifyAccessToken mocks base method.
func (m *MockJwtProvider) VerifyAccessToken(arg0 string) (*jwtprovider.AccessTokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAccessToken", arg0)
	ret0, _ := ret[0].(*jwtprovider.AccessTokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAccessToken indicates an expected call of VerifyAccessToken.
func (mr *MockJwtProviderMockRecorder) VerifyAccessToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAccessToken", reflect.TypeOf((*MockJwtProvider)(nil).VerifyAccessToken), arg0)
}

// VerifyRefreshToken mocks base method.
func (m *MockJwtProvider) VerifyRefreshToken(arg0 string) (*jwtprovider.RefreshTokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRefreshToken", arg0)
	ret0, _ := ret[0].(*jwtprovider.RefreshTokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyRefreshToken indicates an expected call of VerifyRefreshToken.
func (mr *MockJwtProviderMockRecorder) VerifyRefreshToken(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRefreshToken", reflect.TypeOf((*MockJwtProvider)(nil).VerifyRefreshToken), arg0)
}
